name: ha_tien_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  equatable: any
  bloc: any
  flutter_bloc: any
  http: ^0.12.0+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_svg: ^0.18.1
  google_fonts: ^1.1.0
  dio: ^3.0.10
  retrofit: any
  logger: any
  shared_preferences: any
  flutter_hooks: ^0.13.1
  # templates
  easy_text_input: ^1.0.2
  nice_button: ^0.1.7
  bottom_navigation_badge: ^1.0.3
  rxdart: ^0.24.1
  intl: ^0.16.1
  signalr_core: ^1.0.7
  carousel_slider: ^2.3.1
  multi_image_picker: ^4.7.14
  flutter_form_builder: ^3.13.2
  # use for spinner
  commons: ^0.7.8+3
  google_maps_flutter: ^0.5.30
  google_map_location_picker: ^3.3.4
  flutter_localizations:
    sdk: flutter
  geolocator: ^5.3.2+2
  cupertino_tabbar: ^1.1.0
  photo_view: ^0.10.3
  # use for tracking location
  location: ^2.3.5
  flutter_polyline_points: ^0.1.0
  url_launcher: ^5.7.10
  floating_action_bubble: 1.0.9
  # use to custom animated icon button in fab
  animated_icon_button: ^0.3.0
  # use for list
  timeline_list: ^0.0.3
  flutter_keyboard_visibility: ^3.0.0
  flutter_keyboard_size: ^0.1.2+2
  connectivity: ^2.0.2
  flash: ^1.3.1
  modal_bottom_sheet: ^1.0.0+1
  camera_camera: ^1.0.34+1
  image_picker: ^0.6.7+14
  expansion_tile_card: ^1.1.0
  path_provider: ^1.6.27

  #progress bar
  percent_indicator: ^2.1.6
  flutter_tags: ^0.4.9+1
  pin_code_fields: ^6.1.0
  flare_flutter: ^2.0.6
  mapbox_search: ^2.1.0
  permission_handler: ^5.1.0+2
  flutter_webview_plugin: ^0.3.11
  get: ^3.26.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  build_test: any
  flutter_launcher_icons: "^0.8.1"
  flutter_launcher_name: "^0.0.1"
  flutter_native_splash: ^0.1.9
  flutter_automation: ^1.4.0
  maps_toolkit: ^1.1.0+2
  mapbox_search: ^2.1.0
  mapbox_gl: ^0.10.0
  video_player: ^1.0.1
  video_thumbnail: ^0.2.5+1
  google_fonts: ^1.1.2
  flutter_dropdown: ^0.0.8
# This use to set launcher icon
flutter_icons:
  image_path: "assets/icons/icon.jpg"
  android: true
  ios: true
flutter_launcher_name:
  name: "UBND TP.Hà Tiên Cán Bộ"

flutter_native_splash:
  image: assets/icons/splash.png
  color: "#FFFFFF"
  fill: true

  analyzer:
    language:
      enableSuperMixins: true
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #    - assets/images/
    - assets/icons/
    - assets/illustration/
    - assets/images/
    - assets/locales/
